name: Publish npm Package

# Trigger the workflow on push to main or on new tag creation (e.g., v1.0.0)
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Matches tags like v1.0.0, v2.1.3, etc.

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          registry-url: 'https://npm.pkg.github.com/'

      # 3. Cache npm dependencies to speed up builds
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Install dependencies
      - name: Install Dependencies
        run: npm install

      # 5. Run Linting (Optional but recommended)
      - name: Run Lint
        run: npm run lint

      # 6. Run Tests
      - name: Run Tests
        run: npm test

      # 7. Build the Package
      - name: Build Package
        run: npm run build

      # 8. Publish to GitHub Packages
      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}